apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: service-name
  metrics:
  - name: success-rate
    interval: 1m
    successCondition: result[0] >= 0.98
    failureLimit: 2
    provider:
      prometheus:
        address: http://prometheus-server.haproxy-controller.svc.cluster.local:9090
        query: |
          sum(rate(haproxy_backend_http_responses_total{proxy=~".*{{args.service-name}}.*", code=~"2xx|3xx"}[3m])) /
          sum(rate(haproxy_backend_http_responses_total{proxy=~".*{{args.service-name}}.*"}[3m]))
