apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: group1-role
  namespace: dev2
rules:
  - apiGroups:
      - ""            # core api
      - "extensions"
      - "apps"
    resources:
      - "*"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "update"
      - "patch"
      - "delete"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: group1-rolebinding
  namespace: dev2
subjects:
  - kind: Group
    name: group1
roleRef:
  kind: Role
  name: group1-role
  apiGroup: rbac.authorization.k8s.io
