kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: managers-rbac-role
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get", "list", "update", "patch", "watch", "create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: managers-rbac-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: managers-rbac-role
subjects:
- kind: Group
  name: managers-role
  apiGroup: rbac.authorization.k8s.io
