apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev
  name: sa-dev-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-dev-rolebinding
  namespace: dev
subjects:
  - kind: ServiceAccount
    name: sa-dev
    namespace: dev
roleRef:
  kind: Role
  name: sa-dev-role
  apiGroup: rbac.authorization.k8s.io
