apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange1
  namespace: default
spec:
  limits:
  - type: Container
    default:              # 기본limits
      memory: 128Mi
      cpu: 200m
    defaultRequest:      # 기본 requests
      memory: 64Mi
      cpu: 100m
    maxLimitRequestRatio: # limits/requests 비율값
      memory: 2
      cpu: 2
    max:                  # 최대 리소스
      memory: 256Mi
      cpu: 4000m
    min:                  # 최소 리소스
      memory: 32Mi
      cpu: 50m
