apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deploy
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      name: nodeapp
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: stepanowon/nodeapp-slim:1.0.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "100Mi"
            cpu: "64m"
          limits:
            memory: "200Mi"
            cpu: "128m"
