### resource-quota.yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota-sample
  namespace: default
spec:
  hard:
    pods: 4
    requests.cpu: 2
    requests.memory: 2Gi
    limits.cpu: 4
    limits.memory: 4Gi
