# nginx-web-hostpath.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-web
  template:
    metadata:
      name: nodeapp
      labels:
        app: nginx-web
    spec:
      containers:
      - name: ngninx-container
        image: nginx
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: logs-vol
          mountPath: /var/log/nginx
      volumes:
      - name: logs-vol
        hostPath:
          type: Directory
          path: /store
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: lb-port
      port: 80
      targetPort: 80
  selector:
    app: nginx-web
