# store-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: store-pvc
  namespace: default
spec:
  storageClassName: logs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchExpressions:
      - key: type
        operator: In
        values:
          - nfs

