apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-liveness
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: liveness1
        image: stepanowon/nodeapp-liveness:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            httpHeaders:
            - name: health
              value: check
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-lb
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: lb-port
      port: 80
      targetPort: 8080
  selector:
    app: nodeapp
