apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-startup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: startup1
        image: stepanowon/nodeapp-startup:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        # 3초의 지연 후에 3초 간격으로 진단 시작
        # 두번 실패하면 진단 실패로 판단
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-lb
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: lb-port
      port: 80
      targetPort: 8080
  selector:
    app: nodeapp
