apiVersion: v1
kind: Service
metadata:
  name: nginx     # headless service 이름
  labels:
    app: nginx
spec:
  ports:
    - port: 80
      name: web
  clusterIP: None    # headless service는 None 지정
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "nginx"   # headless service의 이름
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: root
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: root
      spec:
        storageClassName: web-nfs-client
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Mi
