apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      name: nodeapp
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: stepanowon/nodeapp-slim:1.0.0
        ports:
        - containerPort: 8080
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nodeapp
            topologyKey: "kubernetes.io/hostname"
