apiVersion: apps/v1
kind: Deployment
metadata:
  name: high-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: high-deploy
  template:
    metadata:
      name: my-nodeapp
      labels:
        app: high-deploy
    spec:
      priorityClassName: "high-priority"
      containers:
      - name: nodeapp
        image: stepanowon/nodeapp-slim:1.0.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 1000Mi
          requests:
            memory: 700Mi


